# Generated by Django 5.1.7 on 2025-03-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='modelComent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(max_length=1000)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
