# Generated by Django 5.1.7 on 2025-03-24 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='modelEda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='modelChoise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=20)),
                ('dopTomato', models.BooleanField(default=False)),
                ('dopCheese', models.BooleanField(default=False)),
                ('dopKolbasa', models.BooleanField(default=False)),
                ('eda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.modeleda')),
            ],
        ),
    ]
