# Generated by Django 5.1.7 on 2025-03-24 16:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_modeleda_modelchoise'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelchoise',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
